apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}{{ .Values.nameOverride }}
  labels:
    app-name: {{ .Chart.Name }}{{ .Values.nameOverride }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app-name: {{ .Chart.Name }}{{ .Values.nameOverride }}
