replicaCount: 1

image:
  repository: registry.digitalocean.com/dp-registry/simple-app
  pullPolicy: IfNotPresent
  tag: 3ac5d9a306d38c5a70b66ceaf3ed93813a989255

nameOverride: "-dev"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: simple-app-dev.whiterr.xyz
      paths:
        - "/"
  tls:
    - secretName: simple-app-tls
      hosts:
        - simple-app-dev.whiterr.xyz
