apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  accounts.admin: apiKey,login
  url: "https://{{ argocd_domain }}"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: {{ argocd_client_id }}
          clientSecret: {{ argocd_client_secret }}
          orgs:
          - name: my-org-123
            teams:
            - main
