apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-dev
spec:
  destination:
    name: ''
    namespace: simple-app-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/charts/simple-app
    repoURL: 'https://github.com/dipaiwin/ga-argocd-do'
    targetRevision: main
    helm:
      valueFiles:
        - simple-app-dev.yml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
