apiVersion: v1
kind: Secret
metadata:
  name: simple-app-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/dipaiwin/ga-argocd-do
  password: {{ github_access_token }}
  username: not-used
