- name: Create namespace
  k8s:
    name: "{{ namespace }}"
    kind: Namespace
    state: present

- name: Download argocd manifest to local.
  get_url:
    url: '{{ item.url }}'
    dest: '~/.manifest/{{ item.name }}'
    mode: '0664'
  loop:
    - { url: 'https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml', name: 'argocd.yaml'  }

- name: Apply argocd manifest to the cluster.
  kubernetes.core.k8s:
    namespace: "{{ namespace }}"
    state: present
    src: "~/.manifest/argocd.yaml"

- name: Create argocd ext manifest
  k8s:
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - argocd-cm.yml
    - argocd-rbac-cm.yml
    - argocd-ingress.yml

- name: deploy argocd repos and apps
  tags: deploy_argocd_config
  k8s:
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - apps/simple-app-repo.yml
    - apps/simple-app-master.yml
    - apps/simple-app-dev.yml
