replicaCount: 3

image:
  repository: registry.digitalocean.com/dp-registry/simple-app
  pullPolicy: IfNotPresent
  tag: 047f547421149256ae16c2d3774da25202f663f9

nameOverride: "-prod"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: simple-app.whiterr.xyz
      paths:
        - "/"
  tls:
    - secretName: simple-app-tls
      hosts:
        - simple-app.whiterr.xyz
